### ISSUE TITLE
AttributeError: Can't get attribute 'Event' on <module '__main__'>

### ISSUE THREAD

**Issue by benchen4395** [buaadk/KJETE#1]
I running the step 4 directly as you said the data have been processed in the data.
The commond 'python matres/joint_model_addcommonseStandModel_roberta_matres.py' will cause the following resut:
"""
Traceback (most recent call last):
  File "matres/joint_model_addcommonseStandModel_roberta_matres.py", line 825, in <module>
    exec_func(args)
  File "matres/joint_model_addcommonseStandModel_roberta_matres.py", line 697, in exec_func
    train_data = EventDataSet(args.data_dir + type_dir, "train")
  File "matres/joint_model_addcommonseStandModel_roberta_matres.py", line 673, in __init__
    self.data = pickle.load(handle)
AttributeError: Can't get attribute 'Event' on <module '__main__' from 'matres/joint_model_addcommonseStandModel_roberta_matres.py'>
""""
So i test the pickle load in the seperate terminal as :
"""
with open('test.pickle', 'rb') as handle:
   ...:     data = pickle.load(handle)
   ...:     data = list(data.values())
   ...: handle.close()
"""
It also shows "AttributeError: Can't get attribute 'Event' on <module '__main__'>"
So could you please provide the right running scripts. Thanks

**Comment by TZWwww** [comment]
hi, have you resolve the problem?
thx!

**Comment by benchen4395** [comment]
> 

No! We fixed it with other method.
However, we failed to reproduce the results in paper with other problems.
The first and most important key is that no data-augmentation code and processed aug_data.pickle is provided, we can't reproduce the same result with the data augmentation method described in the subsec 2.3.
The other key is that we can't get the comparable performances with the pretrained model Roberta. In fact, we get the much lower results of robert-large compared to bert-base/large. It is confusing!!!

**Comment by TZWwww** [comment]
Besides, this work wants to tackle the joint event and relation extraction problem. But I'm curious why they don't have the pipeline extraction results(they only have results by using gold events to extract relations).
